name = "barbearia-wm-caixa"
compatibility_date = "2026-07-04"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "barbearia_wm_db"
database_id = "a8267258-8a0c-408f-8e62-0ffd54acbf09"
