import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BarChart3, ClipboardList, LogOut, Plus, Scissors, Users, WalletCards } from 'lucide-react';
import './style.css';
import logo from '../assets/logo-wm.jpeg';

const money = v => Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
async function api(path, options={}){
  const res = await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});
  const data = await res.json().catch(()=>({}));
  if(!res.ok) throw new Error(data.error||'Erro na operação');
  return data;
}

function Login({onLogin}){const [usuario,setUsuario]=useState('admin'),[senha,setSenha]=useState('123456'),[err,setErr]=useState('');
 async function submit(e){e.preventDefault();setErr('');try{const {user}=await api('/api/login',{method:'POST',body:JSON.stringify({usuario,senha})});localStorage.setItem('wm_user',JSON.stringify(user));onLogin(user)}catch(e){setErr(e.message)}}
 return <main className="login"><section className="loginCard"><img src={logo}/><h1>Fechamento de Caixa</h1><p>Barbearia WM • Comandas digitais e comissão automática</p><form onSubmit={submit}><label>Usuário<input value={usuario} onChange={e=>setUsuario(e.target.value)} /></label><label>Senha<input type="password" value={senha} onChange={e=>setSenha(e.target.value)} /></label>{err&&<div className="alert">{err}</div>}<button>Entrar no sistema</button></form><small>Acesso inicial: admin / 123456</small></section></main>}

function Shell({user,setUser}){const [tab,setTab]=useState('dashboard');function out(){localStorage.removeItem('wm_user');setUser(null)}
 const nav=[['dashboard',BarChart3,'Dashboard'],['comanda',ClipboardList,'Nova comanda'],['colaboradores',Users,'Colaboradores'],['servicos',Scissors,'Serviços'],['relatorios',WalletCards,'Relatórios']];
 return <div className="app"><aside><div className="brand"><img src={logo}/><div><b>Barbearia WM</b><span>Caixa Digital</span></div></div><nav>{nav.map(([id,Icon,t])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={18}/>{t}</button>)}</nav><button className="logout" onClick={out}><LogOut size={18}/>Sair</button></aside><section className="content"><header><div><h2>{nav.find(n=>n[0]===tab)?.[2]}</h2><p>Olá, {user.nome}</p></div><span className="pill">{user.role}</span></header>{tab==='dashboard'&&<Dashboard/>}{tab==='comanda'&&<Comanda user={user}/>} {tab==='colaboradores'&&<Colaboradores/>}{tab==='servicos'&&<Servicos/>}{tab==='relatorios'&&<Relatorios/>}</section></div>}

function Dashboard(){const [r,setR]=useState(null);useEffect(()=>{api('/api/relatorios?periodo=dia').then(setR)},[]); if(!r)return <p>Carregando...</p>;
 return <><div className="cards"><Card title="Faturamento hoje" value={money(r.total.faturamento)}/><Card title="Atendimentos" value={r.total.atendimentos}/><Card title="Bebidas" value={money(r.total.bebidas)}/><Card title="Comissões" value={money(r.total.comissoes)}/></div><div className="panel"><h3>Produtividade do dia</h3><Table rows={r.colaboradores}/></div></>}
function Card({title,value}){return <div className="card"><span>{title}</span><strong>{value}</strong></div>}
function Table({rows=[]}){return <div className="table"><table><thead><tr><th>Colaborador</th><th>Atend.</th><th>Faturamento</th><th>Bebidas</th><th>Comissão</th><th>Empresa</th></tr></thead><tbody>{rows.map((x,i)=><tr key={i}><td>{x.colaborador}</td><td>{x.atendimentos}</td><td>{money(x.faturamento)}</td><td>{money(x.bebidas)}</td><td>{money(x.comissao)}</td><td>{money(x.empresa)}</td></tr>)}</tbody></table></div>}

function Comanda({user}){const [servicos,setServicos]=useState([]),[cols,setCols]=useState([]),[cliente,setCliente]=useState(''),[col,setCol]=useState(user.role==='colaborador'?user.id:''),[pag,setPag]=useState('Pix'),[itens,setItens]=useState([]),[msg,setMsg]=useState('');
 useEffect(()=>{api('/api/servicos').then(d=>setServicos(d.servicos));api('/api/colaboradores').then(d=>setCols(d.colaboradores.filter(c=>c.ativo)))},[]);
 const total=useMemo(()=>itens.reduce((s,i)=>s+Number(i.valor||0),0),[itens]);
 function add(s){setItens([...itens,{service_id:s.id,descricao:s.nome,valor:s.preco||'',tipo:s.tipo,comissionavel:s.comissionavel}])}
 async function salvar(){setMsg('');try{await api('/api/comandas',{method:'POST',body:JSON.stringify({cliente,colaborador_id:col,forma_pagamento:pag,itens})});setCliente('');setItens([]);setMsg('Comanda salva com sucesso ✅')}catch(e){setMsg(e.message)}}
 return <div className="grid2"><div className="panel"><h3>Dados da comanda</h3><label>Cliente<input value={cliente} onChange={e=>setCliente(e.target.value)} placeholder="Nome do cliente"/></label><label>Colaborador<select value={col} onChange={e=>setCol(e.target.value)} disabled={user.role==='colaborador'}><option value="">Selecione</option>{cols.map(c=><option key={c.id} value={c.id}>{c.nome} • {c.percentual_comissao}%</option>)}</select></label><label>Forma de pagamento<select value={pag} onChange={e=>setPag(e.target.value)}>{['Pix','Dinheiro','Débito','Crédito'].map(p=><option key={p}>{p}</option>)}</select></label><h4>Serviços / Produtos</h4><div className="chips">{servicos.map(s=><button key={s.id} onClick={()=>add(s)} className={s.tipo==='bebida'?'drink':''}><Plus size={14}/>{s.nome}</button>)}</div></div><div className="panel"><h3>Itens lançados</h3>{itens.length===0&&<p className="muted">Nenhum item adicionado.</p>}{itens.map((i,idx)=><div className="item" key={idx}><span>{i.descricao}<small>{i.tipo==='bebida'?'Sem comissão':'Comissão'}</small></span><input type="number" value={i.valor} onChange={e=>{const n=[...itens];n[idx].valor=e.target.value;setItens(n)}} placeholder="0,00"/><button onClick={()=>setItens(itens.filter((_,j)=>j!==idx))}>×</button></div>)}<div className="total"><span>Total</span><b>{money(total)}</b></div>{msg&&<div className="ok">{msg}</div>}<button className="primary" onClick={salvar}>Salvar comanda</button></div></div>}

function Colaboradores(){const [list,setList]=useState([]),[form,setForm]=useState({nome:'',usuario:'',senha:'',percentual_comissao:50}); const load=()=>api('/api/colaboradores').then(d=>setList(d.colaboradores)); useEffect(load,[]); async function save(e){e.preventDefault();await api('/api/colaboradores',{method:'POST',body:JSON.stringify(form)});setForm({nome:'',usuario:'',senha:'',percentual_comissao:50});load()} return <div className="grid2"><form className="panel" onSubmit={save}><h3>Novo colaborador</h3><label>Nome<input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></label><label>Usuário<input value={form.usuario} onChange={e=>setForm({...form,usuario:e.target.value})}/></label><label>Senha<input value={form.senha} onChange={e=>setForm({...form,senha:e.target.value})}/></label><label>Comissão %<input type="number" value={form.percentual_comissao} onChange={e=>setForm({...form,percentual_comissao:e.target.value})}/></label><button className="primary">Cadastrar</button></form><div className="panel"><h3>Equipe</h3>{list.map(c=><div className="row" key={c.id}><b>{c.nome}</b><span>{c.usuario} • {c.percentual_comissao}% • {c.role}</span></div>)}</div></div>}
function Servicos(){const [list,setList]=useState([]),[form,setForm]=useState({nome:'',preco:0,tipo:'servico'}); const load=()=>api('/api/servicos').then(d=>setList(d.servicos));useEffect(load,[]);async function save(e){e.preventDefault();await api('/api/servicos',{method:'POST',body:JSON.stringify(form)});setForm({nome:'',preco:0,tipo:'servico'});load()} return <div className="grid2"><form className="panel" onSubmit={save}><h3>Novo serviço/produto</h3><label>Nome<input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></label><label>Preço padrão<input type="number" value={form.preco} onChange={e=>setForm({...form,preco:e.target.value})}/></label><label>Tipo<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}><option value="servico">Serviço com comissão</option><option value="bebida">Bebida sem comissão</option></select></label><button className="primary">Cadastrar</button></form><div className="panel"><h3>Tabela</h3>{list.map(s=><div className="row" key={s.id}><b>{s.nome}</b><span>{money(s.preco)} • {s.tipo==='bebida'?'sem comissão':'comissão'}</span></div>)}</div></div>}
function Relatorios(){const [periodo,setPeriodo]=useState('dia'),[r,setR]=useState(null);useEffect(()=>{api('/api/relatorios?periodo='+periodo).then(setR)},[periodo]); return <div className="panel"><div className="toolbar"><h3>Relatório</h3><select value={periodo} onChange={e=>setPeriodo(e.target.value)}><option value="dia">Diário</option><option value="semana">Semanal</option><option value="mes">Mensal</option></select><button onClick={()=>window.print()}>Exportar PDF</button></div>{r&&<><div className="cards"><Card title="Faturamento" value={money(r.total.faturamento)}/><Card title="Comissões" value={money(r.total.comissoes)}/><Card title="Bebidas" value={money(r.total.bebidas)}/><Card title="Atendimentos" value={r.total.atendimentos}/></div><Table rows={r.colaboradores}/></>}</div>}
function App(){const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('wm_user')||'null'));return user?<Shell user={user} setUser={setUser}/>:<Login onLogin={setUser}/>}

createRoot(document.getElementById('root')).render(<App/>);
